# This is a basic workflow to help you get started with Actions

name: CI PlantUML

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    paths: 
    - .github/workflow/ci-plantuml.yml
    -  docs/diagram-dependencies.puml
    

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: PlantUML

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checks-out your repository
      uses: actions/checkout@v2

    - name: Install Dependencies (graphviz,default-jre, plantuml)
      run: sudo apt-get install graphviz default-jre plantuml

    - name: Diagrams
      env:
        DIAGRAM_DEPENDENCIES_PATH: docs/diagram-dependencies.puml
      run:  plantuml -v -tpng  ${DIAGRAM_DEPENDENCIES_PATH}
    - name: Commit Changes
      env:
        DIAGRAM_DEPENDENCIES_PNG: docs/dependencies.png
        GH_TOKEN: ${{secrets.GH_ACTIONS_TOKEN}}
        GH_REPOSITORY: diegotony/flask-project-template
        EMAIL: ${{secrets.GH_EMAIL}}
        NAME: ${{secrets.GH_NAME}}
      run: |
        git add "$DIAGRAM_DEPENDENCIES_PNG"
        git config user.email "$EMAIL"
        git config user.name "$NAME"

        git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${GH_REPOSITORY}.git
        BRANCH=$(echo -n "$GITHUB_REF" | sed 's_^refs/heads/__')
        git checkout ${BRANCH}
        git diff --quiet && git diff --staged --quiet || {
          git commit -m "Auto Update Diagram-Dependencies" ;
          git push origin ${BRANCH}
        }

